# Generated by Django 4.2.15 on 2024-08-30 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(max_length=200)),
                ('dSummary', models.TextField(help_text='Enter a description of the department', max_length=1000)),
            ],
            options={
                'ordering': ['dName'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Employee', primary_key=True, serialize=False)),
                ('eName', models.CharField(max_length=200)),
                ('birthDate', models.DateField(help_text="Enter the employee's birth date")),
                ('eRusume', models.TextField(help_text='Enter the description of this staff', max_length=1000)),
                ('hireDate', models.DateField(help_text="Enter the employee's hired date")),
                ('eSalary', models.DecimalField(decimal_places=2, help_text="Enter the employee's monthly salary", max_digits=10)),
            ],
            options={
                'ordering': ['eName'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(help_text='Enter a position (e.g. Driver ...)', max_length=200, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pName'), name='position_pname_case_insensitive_unique', violation_error_message='Genre already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(help_text='Select a department for this employee', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(help_text='Select a position for this employee', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.position'),
        ),
        migrations.AddField(
            model_name='department',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text='Select a position for this department', null=True, to='catalog.position'),
        ),
    ]
