# Generated by Django 4.2.15 on 2024-09-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_erusume_employee_eresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(help_text='Start time')),
                ('endTime', models.TimeField(help_text='End time')),
                ('lineNumber', models.PositiveIntegerField(help_text='set a unique line number', unique=True)),
                ('Price', models.DecimalField(decimal_places=2, help_text='set a price', max_digits=10)),
                ('description', models.TextField(help_text='describe this bus line')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(help_text='Enter a staion name', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='StaionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('station', models.ForeignKey(help_text='select a staion', on_delete=django.db.models.deletion.RESTRICT, to='catalog.station')),
            ],
        ),
    ]
