# Generated by Django 4.2.15 on 2024-09-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_busline_station_staionsequence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaionSequence',
            new_name='StationSequence',
        ),
    ]
