# Generated by Django 4.2.15 on 2024-09-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_staionsequence_stationsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='busline',
            name='status',
            field=models.CharField(choices=[('m', '维护中'), ('o', '运营中'), ('b', '建设中')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('m', '维护中'), ('o', '运营中'), ('b', '建设中')], default='b', max_length=1),
        ),
    ]
