# Generated by Django 4.2.15 on 2024-09-05 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_busline_status_station_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsequence',
            name='busline',
            field=models.ForeignKey(help_text='select a busline', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.busline'),
        ),
    ]
