# Generated by Django 4.2.15 on 2024-09-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_stationsequence_busline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sName',
            field=models.CharField(help_text='Enter a staion name', max_length=200, unique=True),
        ),
    ]
