# Generated by Django 4.2.15 on 2024-09-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_stationsequence_busline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vModel', models.CharField(max_length=200, unique=True)),
                ('vType', models.CharField(choices=[('n', '普通巴士'), ('m', '微型公交'), ('j', '铰接式公交车')], default='n', max_length=1)),
                ('manufacturer', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(help_text='Please input the capacity of this vehicle')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of this vehicle', max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
