# Generated by Django 4.2.15 on 2024-09-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vType',
            field=models.CharField(choices=[('n', '普通公交车'), ('m', '微型公交车'), ('j', '大型公交车'), ('c', '柴油公交车'), ('d', '电动公交车')], default='n', max_length=1),
        ),
    ]
