# Generated by Django 4.2.15 on 2024-09-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_vehicle_price_alter_vehicle_vtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInstance',
            fields=[
                ('plateNumber', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_maintenance_date', models.TimeField(blank=True)),
                ('produce_date', models.TimeField(help_text='Input the produced date')),
                ('status', models.CharField(choices=[('m', '维护中'), ('o', '运营中')], default='o', max_length=1)),
                ('busline', models.ForeignKey(help_text='choose a bus-line', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.busline')),
                ('vehicle', models.ForeignKey(help_text='Choose a vehicle', on_delete=django.db.models.deletion.RESTRICT, to='catalog.vehicle')),
            ],
        ),
    ]
