# Generated by Django 4.2.15 on 2024-09-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_vehicleinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinstance',
            name='last_maintenance_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicleinstance',
            name='produce_date',
            field=models.DateField(help_text='Input the produced date'),
        ),
    ]
