# Generated by Django 4.2.15 on 2024-09-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_vehicleinstance_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinstance',
            name='plateNumber',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
